export const leftDelimiters = new Set<string>();
leftDelimiters.add("{");
leftDelimiters.add("|");
leftDelimiters.add("\\|");
leftDelimiters.add("(");
leftDelimiters.add("\\{");
leftDelimiters.add("\\lceil");
leftDelimiters.add("\\ulcorner");
leftDelimiters.add("[");
leftDelimiters.add("\\langle");
leftDelimiters.add("\\lfloor");
leftDelimiters.add("\\llcorner");

export const rightDelimiters = new Set<string>();
rightDelimiters.add("}");
rightDelimiters.add("|");
rightDelimiters.add("\\|");
rightDelimiters.add(")");
rightDelimiters.add("\\}");
rightDelimiters.add("\\rceil");
rightDelimiters.add("\\urcorner");
rightDelimiters.add("]");
rightDelimiters.add("\\rangle");
rightDelimiters.add("\\rfloor");
rightDelimiters.add("lrcorner");
